import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Template from "./template";

import Navigation from "./components/Navigation"

export const metadata: Metadata = {
  title: "Create Next App Dev101",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, //A propriedade 'children' é recebida como um parâmetro
}: Readonly<{
  children: React.ReactNode; // 'children' deve ser do tipo React.ReactNode
}>) {
  const navLinks =  [
    {
      name: 'Home',
      href: "/"
    },
    {
      name: 'Dashboard',
      href: '/dashboard'
    },
    {
      name: 'Blog',
      href: '/blog'
    }
  ]
  return ( // O componente retorna uma estrutura HTML básica, onde devemos aplicar o conteudo todo em comum da aplicação
    <html lang="en">
      <body>
       <Navigation navLinks={navLinks} />
        {children} {/* O conteúdo do componente 'RootLayout' é renderizado aqui */}        
        </body>
    </html>
  );
}
