import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Template from "./template";

export const metadata: Metadata = {
  title: "Create Next App Dev101",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, //A propriedade 'children' é recebida como um parâmetro
}: Readonly<{
  children: React.ReactNode; // 'children' deve ser do tipo React.ReactNode
}>) {
  const valor = Math.floor(Math.random() * 20)
  return ( // O componente retorna uma estrutura HTML básica, onde devemos aplicar o conteudo todo em comum da aplicação
    <html lang="en">
      <body>
        <nav className="bg-red-600">
          <ul>
            <li>{valor}</li>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/dashboard">Dashboard</Link></li>            
          </ul>
        </nav>
        {children} {/* O conteúdo do componente 'RootLayout' é renderizado aqui */}        
        </body>
    </html>
  );
}
